name: ai_assistant
dependencies:
    - python=3.*
    - pip
    - pip:
      - litestar
      - sentence-transformers
      - faiss-cpu
      - pypdf
      - jax[cuda13]
      - gemma
      - llama-cpp-python #Best decide between llama and gemma here!
      - numpy
